# Generated by Django 3.0.5 on 2020-08-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viatura', '0001_initial'),
        ('observacao', '0001_initial'),
        ('guarnicao', '0001_initial'),
        ('policial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(help_text='Informe a Função', max_length=50, verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'db_table': 'funcao',
            },
        ),
        migrations.CreateModel(
            name='PolicialViatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmsaida', models.CharField(blank=True, help_text='Informe a Quilometragem de saída', max_length=10, verbose_name='Quilometragem de saída')),
                ('kmvolta', models.CharField(blank=True, help_text='Informe a Quilometragem de volta', max_length=10, verbose_name='Quilometragem de volta')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('condicaoviatura', models.ForeignKey(blank=True, help_text='Informe as condições da viatura', null=True, on_delete=django.db.models.deletion.CASCADE, to='observacao.Observacao', verbose_name='Observações das condições da viatura')),
                ('funcao', models.ForeignKey(help_text='Selecione a função do policial', on_delete=django.db.models.deletion.CASCADE, to='policialviatura.Funcao', verbose_name='Função')),
                ('guarnicao', models.ForeignKey(help_text='Selecione a guarnição', on_delete=django.db.models.deletion.CASCADE, to='guarnicao.Guarnicao', verbose_name='Guarnição')),
                ('policial', models.ForeignKey(help_text='Selecione o policial', on_delete=django.db.models.deletion.CASCADE, to='policial.Policial', verbose_name='Policial')),
                ('viatura', models.ForeignKey(blank=True, help_text='Selecione a viatura', null=True, on_delete=django.db.models.deletion.CASCADE, to='viatura.Viatura', verbose_name='Viatura')),
            ],
            options={
                'verbose_name': 'Policial Viatura',
                'verbose_name_plural': 'Policiais Viatura',
                'db_table': 'policialviatura',
            },
        ),
    ]
