# Generated by Django 3.0.5 on 2020-09-17 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observacao', '0001_initial'),
        ('policialviatura', '0002_policialviatura_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='policialviatura',
            name='observacao',
            field=models.ForeignKey(blank=True, help_text='Selecione a observação', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guarnicao_observacao', to='observacao.Observacao', verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='policialviatura',
            name='condicaoviatura',
            field=models.ForeignKey(blank=True, help_text='Informe a condição da viatura', null=True, on_delete=django.db.models.deletion.CASCADE, to='observacao.Observacao', verbose_name='Observações das condições da viatura'),
        ),
    ]
