# Generated by Django 3.0.5 on 2020-09-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policialviatura', '0003_auto_20200917_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policialviatura',
            name='observacao',
        ),
    ]
