# Generated by Django 3.0.5 on 2020-08-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batalhao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batalhao', models.CharField(help_text='Informe o Batalhão', max_length=100, verbose_name='Batalhão')),
            ],
            options={
                'verbose_name': 'Batalhão',
                'verbose_name_plural': 'Batalhões',
                'db_table': 'batalhao',
            },
        ),
        migrations.CreateModel(
            name='BatalhaoMunicipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batalhao', models.ForeignKey(help_text='Informe o Batalhão', on_delete=django.db.models.deletion.CASCADE, to='batalhao.Batalhao', verbose_name='Batalhão')),
                ('municipio', models.ForeignKey(help_text='Informe o Município', on_delete=django.db.models.deletion.CASCADE, to='endereco.Municipios', verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Municipios do Batalhão',
                'verbose_name_plural': 'Municipios dos Batalhões',
                'db_table': 'batalhaomunicipios',
            },
        ),
    ]
