# Generated by Django 3.0.5 on 2020-08-20 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rat', '0002_auto_20200819_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratveiculoenvolvidos',
            name='ratveiculos',
            field=models.ForeignKey(help_text='Informe o veículo', on_delete=django.db.models.deletion.CASCADE, to='rat.RATVeiculos', verbose_name='Veículo'),
        ),
    ]
