# Generated by Django 3.0.5 on 2020-08-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rat', '0003_auto_20200820_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratveiculos',
            name='condutor',
            field=models.BooleanField(default=True, help_text='Informe se o condutor está presente', verbose_name='Condutor presente?'),
            preserve_default=False,
        ),
    ]
