# Generated by Django 3.0.5 on 2020-09-15 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policial', '0001_initial'),
        ('rat', '0004_ratveiculos_condutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rat',
            name='finalizadopor',
            field=models.ForeignKey(blank=True, help_text='Finalizado por', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rat_finalizadopor', to='policial.Policial', verbose_name='Finalizado por'),
        ),
    ]
