# Generated by Django 3.0.5 on 2020-08-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companhia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companhia', models.CharField(help_text='Informe a companhia', max_length=50, verbose_name='Companhia')),
            ],
            options={
                'verbose_name': 'Companhia',
                'verbose_name_plural': 'Companhias',
                'db_table': 'companhia',
            },
        ),
        migrations.CreateModel(
            name='Guarnicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatorio', models.TextField(blank=True, null=True, verbose_name='Relatório de guarnição')),
                ('dataabertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de abertura')),
                ('datafechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de fechamento')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Guarnição',
                'verbose_name_plural': 'Guarnições',
                'db_table': 'guarnicao',
            },
        ),
        migrations.CreateModel(
            name='ModalidadedePoliciamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(help_text='Informe a modalidade de policiamento', max_length=50, verbose_name='Modalidade de Policiamento')),
            ],
            options={
                'verbose_name': 'Modalidade de policiamento',
                'verbose_name_plural': 'Modalidades de policiamento',
                'db_table': 'modalidadepoliciamento',
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiposervico', models.CharField(help_text='Informe o tipo de serviço', max_length=50, verbose_name='Tipo de Serviço')),
            ],
            options={
                'verbose_name': 'Tipo de serviço',
                'verbose_name_plural': 'Tipos de serviço',
                'db_table': 'tiposervico',
            },
        ),
        migrations.CreateModel(
            name='GuarnicaoTRAV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Informe o código TRAV extraído', max_length=20, verbose_name='TRAV extraído')),
                ('tipoveiculo', models.CharField(choices=[('carro', 'CARRO'), ('moto', 'MOTO')], help_text='Informe o tipo de veículo', max_length=5, verbose_name='Tipo de veículo')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('guarnicao', models.ForeignKey(help_text='Informe a guarnição', on_delete=django.db.models.deletion.CASCADE, to='guarnicao.Guarnicao', verbose_name='Guarnição')),
            ],
            options={
                'verbose_name': 'TRAV da guarnição',
                'verbose_name_plural': 'TRAVs das guarnições',
                'db_table': 'guarnicaotrav',
            },
        ),
        migrations.CreateModel(
            name='GuarnicaoRRD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Informe o código RRD extraído', max_length=20, verbose_name='RRD extraído')),
                ('tipoveiculo', models.CharField(choices=[('carro', 'CARRO'), ('moto', 'MOTO')], help_text='Informe o tipo de veículo', max_length=5, verbose_name='Tipo de veículo')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('guarnicao', models.ForeignKey(help_text='Informe a guarnição', on_delete=django.db.models.deletion.CASCADE, to='guarnicao.Guarnicao', verbose_name='Guarnição')),
            ],
            options={
                'verbose_name': 'RRD da guarnição',
                'verbose_name_plural': 'RRDs das guarnições',
                'db_table': 'guarnicaorrd',
            },
        ),
        migrations.CreateModel(
            name='GuarnicaoAIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Informe o código AIT extraído', max_length=20, verbose_name='AIT extraído')),
                ('tipoveiculo', models.CharField(choices=[('carro', 'CARRO'), ('moto', 'MOTO')], help_text='Informe o tipo de veículo', max_length=5, verbose_name='Tipo de veículo')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('guarnicao', models.ForeignKey(help_text='Informe a guarnição', on_delete=django.db.models.deletion.CASCADE, to='guarnicao.Guarnicao', verbose_name='Guarnição')),
            ],
            options={
                'verbose_name': 'AIT da guarnição',
                'verbose_name_plural': 'AITs das guarnições',
                'db_table': 'guarnicaoait',
            },
        ),
    ]
