# Generated by Django 3.0.5 on 2020-08-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guarnicao', '0001_initial'),
        ('policial', '0001_initial'),
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarnicao',
            name='comandante',
            field=models.ForeignKey(help_text='Informe quem é o comandante', on_delete=django.db.models.deletion.CASCADE, to='policial.Policial', verbose_name='Comandante da guarnição'),
        ),
        migrations.AddField(
            model_name='guarnicao',
            name='companhia',
            field=models.ForeignKey(help_text='Informe a Companhia', on_delete=django.db.models.deletion.CASCADE, to='guarnicao.Companhia', verbose_name='Companhia'),
        ),
        migrations.AddField(
            model_name='guarnicao',
            name='coordenadordearea',
            field=models.ForeignKey(help_text='Informe o coordenador de área', on_delete=django.db.models.deletion.CASCADE, related_name='coordenadordearea', to='policial.Policial', verbose_name='Coordenador de área'),
        ),
        migrations.AddField(
            model_name='guarnicao',
            name='modalidadepoliciamento',
            field=models.ForeignKey(help_text='Informe a modalidade de policiamento', on_delete=django.db.models.deletion.CASCADE, to='guarnicao.ModalidadedePoliciamento', verbose_name='Modalidade de policiamento'),
        ),
        migrations.AddField(
            model_name='guarnicao',
            name='municipio',
            field=models.ForeignKey(help_text='Informe o município atuante', on_delete=django.db.models.deletion.CASCADE, to='endereco.Municipios', verbose_name='Município atuante'),
        ),
        migrations.AddField(
            model_name='guarnicao',
            name='tiposervico',
            field=models.ForeignKey(help_text='Informe o tipo de serviço', on_delete=django.db.models.deletion.CASCADE, to='guarnicao.TipoServico', verbose_name='Tipo de Serviço'),
        ),
        migrations.AddField(
            model_name='companhia',
            name='comandante',
            field=models.ForeignKey(blank=True, help_text='Informe o comandante da companhia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comandante_companhia', to='policial.Policial', verbose_name='Comandante'),
        ),
    ]
