# Generated by Django 3.0.5 on 2020-09-17 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarnicao', '0004_auto_20200915_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarnicao',
            name='finalizadopor',
        ),
    ]
