# Generated by Django 3.0.5 on 2020-09-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policial', '0001_initial'),
        ('guarnicao', '0007_auto_20200917_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarnicao',
            name='bloqueadopor',
            field=models.ForeignKey(blank=True, help_text='Bloqueado por', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guarnicao_bloqueadopor', to='policial.Policial', verbose_name='Bloqueado por'),
        ),
        migrations.AlterField(
            model_name='guarnicao',
            name='desbloqueadopor',
            field=models.ForeignKey(blank=True, help_text='Desbloqueado por', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guarnicao_desbloqueadopor', to='policial.Policial', verbose_name='Desbloqueado por'),
        ),
    ]
