# Generated by Django 3.0.5 on 2020-09-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarnicao', '0009_auto_20200917_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarnicao',
            name='desbloqueadopor',
        ),
    ]
