# Generated by Django 3.0.5 on 2020-10-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guarnicao', '0012_permuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permuta',
            name='guarnicao_nova',
            field=models.ForeignKey(blank=True, help_text='Informe a nova guarnição', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permuta_guarnicaonova', to='guarnicao.Guarnicao', verbose_name='Nova guarnição'),
        ),
    ]
