# Generated by Django 3.0.5 on 2020-08-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rat', '0001_initial'),
        ('ocorrencia', '0001_initial'),
        ('envolvido', '0001_initial'),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envolvido',
            name='ocorrencia',
            field=models.ForeignKey(blank=True, help_text='Informe a ocorrência', null=True, on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.Ocorrencia', verbose_name='Ocorrência'),
        ),
        migrations.AddField(
            model_name='envolvido',
            name='pessoa',
            field=models.ForeignKey(blank=True, help_text='Informe a pessoa', null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa', verbose_name='Pessoa'),
        ),
        migrations.AddField(
            model_name='envolvido',
            name='rat',
            field=models.ForeignKey(blank=True, help_text='Informe o Registro de Acidente de Trânsito', null=True, on_delete=django.db.models.deletion.CASCADE, to='rat.RAT', verbose_name='Registro de Acidente de Trânsito'),
        ),
        migrations.AddField(
            model_name='envolvido',
            name='tipoenvolvimento',
            field=models.ForeignKey(help_text='Informe o tipo de envolvimento', on_delete=django.db.models.deletion.CASCADE, to='envolvido.TipoEnvolvimento', verbose_name='Tipo de envolvimento'),
        ),
    ]
