# Generated by Django 3.0.5 on 2020-08-19 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observacao', '0001_initial'),
        ('envolvido', '0002_auto_20200813_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='envolvido',
            name='observacao',
            field=models.ForeignKey(blank=True, help_text='Informe a Observação', null=True, on_delete=django.db.models.deletion.CASCADE, to='observacao.Observacao', verbose_name='Observação'),
        ),
    ]
