# Generated by Django 3.0.5 on 2020-08-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localrecebedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envolvido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('agenterecebedor', models.ForeignKey(blank=True, help_text='Selecione o local destinado', null=True, on_delete=django.db.models.deletion.CASCADE, to='localrecebedor.AgenteRecebedor', verbose_name='Agente recebedor')),
                ('localrecebedor', models.ForeignKey(blank=True, help_text='Selecione o local destinado', null=True, on_delete=django.db.models.deletion.CASCADE, to='localrecebedor.LocalRecebedor', verbose_name='Local destinado')),
            ],
            options={
                'verbose_name': 'Envolvido',
                'verbose_name_plural': 'Envolvidos',
                'db_table': 'envolvido',
            },
        ),
        migrations.CreateModel(
            name='TipoEnvolvimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Informe o tipo de envolvimento', max_length=20, verbose_name='Tipo de envolvimento')),
                ('rat', models.BooleanField(default=False, help_text='É RAT?', verbose_name='Registro de Acidente de Trânsito')),
            ],
            options={
                'verbose_name': 'Tipo de envolvimento',
                'verbose_name_plural': 'Tipos de envolvimento',
                'db_table': 'tipoenvolvimento',
            },
        ),
        migrations.CreateModel(
            name='TipoLesao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Informe o tipo de lesão', max_length=50, verbose_name='Tipo de lesão')),
            ],
            options={
                'verbose_name': 'Tipo de lesão',
                'verbose_name_plural': 'Tipos de lesão',
                'db_table': 'tipolesao',
            },
        ),
        migrations.CreateModel(
            name='Lesao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descreva a lesão', max_length=255, verbose_name='Descrição da lesão')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('envolvido', models.ForeignKey(help_text='Informe o envolvido', on_delete=django.db.models.deletion.CASCADE, to='envolvido.Envolvido', verbose_name='Envolvido')),
                ('tipolesao', models.ForeignKey(help_text='Informe o tipo de lesão', on_delete=django.db.models.deletion.CASCADE, to='envolvido.TipoLesao', verbose_name='Tipo de lesão')),
            ],
            options={
                'verbose_name': 'Lesão',
                'verbose_name_plural': 'Lesões',
                'db_table': 'lesao',
            },
        ),
    ]
