# Generated by Django 3.0.5 on 2020-08-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('codigo_uf', models.IntegerField(help_text='Informe o código UF', primary_key=True, serialize=False, verbose_name='Código UF')),
                ('uf', models.CharField(help_text='Informe a UF', max_length=2, verbose_name='UF')),
                ('nome', models.CharField(help_text='Informe o nome do Estado', max_length=100, verbose_name='Nome do Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('codigo_ibge', models.IntegerField(help_text='Informe o código do IBGE', primary_key=True, serialize=False, verbose_name='Código IBGE')),
                ('nome', models.CharField(help_text='Informe o nome da cidade', max_length=100, verbose_name='Nome da cidade')),
                ('latitude', models.FloatField(help_text='Informe a latitude', max_length=8, verbose_name='Latitude')),
                ('longitude', models.FloatField(help_text='Informe a longitude', max_length=8, verbose_name='Longitude')),
                ('capital', models.BooleanField(help_text='Informe se este município é a capital', verbose_name='É a capital?')),
                ('codigo_uf', models.ForeignKey(help_text='Informe o código UF', on_delete=django.db.models.deletion.CASCADE, to='endereco.Estados', verbose_name='Código UF')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'db_table': 'municipios',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Informe o numero', max_length=20, null=True, verbose_name='Número')),
                ('rua', models.CharField(help_text='Informe a rua', max_length=50, verbose_name='Rua')),
                ('bairro', models.CharField(help_text='Informe o bairro', max_length=50, verbose_name='Bairro')),
                ('complemento', models.TextField(blank=True, help_text='Informe o complemento', verbose_name='Complemento')),
                ('latitude', models.FloatField(blank=True, help_text='Informe a Latitude', max_length=8, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, help_text='Informe a Longitude', max_length=8, null=True, verbose_name='Longitude')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('municipio', models.ForeignKey(help_text='Selecione o município', on_delete=django.db.models.deletion.CASCADE, to='endereco.Municipios', verbose_name='Município')),
                ('observacao', models.ForeignKey(blank=True, help_text='Informe a observação', null=True, on_delete=django.db.models.deletion.CASCADE, to='observacao.Observacao', verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'endereco',
            },
        ),
    ]
