# Generated by Django 3.0.5 on 2020-08-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Informe o tipo de anexo', max_length=50, verbose_name='Tipo de anexo')),
            ],
            options={
                'verbose_name': 'Tipo de anexo',
                'verbose_name_plural': 'Tipos de anexo',
                'db_table': 'tipoanexo',
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, help_text='Informe a URL', max_length=255, null=True, verbose_name='URL')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('observacao', models.ForeignKey(help_text='Informe a observação', on_delete=django.db.models.deletion.CASCADE, to='observacao.Observacao', verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'db_table': 'anexo',
            },
        ),
    ]
