# Generated by Django 3.0.5 on 2020-08-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo', '0002_auto_20200813_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo',
            name='url',
        ),
        migrations.AddField(
            model_name='anexo',
            name='anexo',
            field=models.FileField(default=1, upload_to='anexos/'),
            preserve_default=False,
        ),
    ]
