# Generated by Django 3.0.5 on 2020-09-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anexo', '0004_auto_20200820_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo',
            name='tipoanexo',
        ),
        migrations.DeleteModel(
            name='TipoAnexo',
        ),
    ]
