# Generated by Django 3.0.5 on 2020-08-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome', max_length=50, verbose_name='Nome')),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], help_text='Informe o sexo', max_length=1, verbose_name='Sexo')),
                ('datanascimento', models.DateField(blank=True, help_text='Informe a data de nascimento', null=True, verbose_name='Data de nascimento')),
                ('mae', models.CharField(blank=True, help_text='Informe o nome da mãe', max_length=50, verbose_name='Nome da mãe')),
                ('apelido', models.CharField(blank=True, help_text='Informe o apelido', max_length=25, verbose_name='Apelido')),
                ('cpf', models.CharField(blank=True, help_text='Informe o CPF', max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, help_text='Informe o RG', max_length=14, verbose_name='RG')),
                ('cnh', models.CharField(blank=True, help_text='Informe a CNH', max_length=30, verbose_name='CNH')),
                ('datavencimentocnh', models.DateField(blank=True, help_text='Informe a data de vencimento da CNH', null=True, verbose_name='Data de vencimento da CNH')),
                ('categoriacnh', models.CharField(blank=True, help_text='Informe a categoria da CNH', max_length=5, null=True, verbose_name='Categoria da CNH')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='PessoaEndereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('endereco', models.ForeignKey(help_text='Informe o endereço', on_delete=django.db.models.deletion.CASCADE, to='endereco.Endereco', verbose_name='Endereço')),
                ('pessoa', models.ForeignKey(help_text='Informe a pessoa', on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Endereço de pessoa',
                'verbose_name_plural': 'Endereços de pessoa',
                'db_table': 'pessoaendereco',
            },
        ),
    ]
