# Generated by Django 3.0.5 on 2020-08-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculo', '0001_initial'),
        ('observacao', '0001_initial'),
        ('localrecebedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoriosOcorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Apreensão da ocorrência',
                'verbose_name_plural': 'Apreensões da ocorrência',
                'db_table': 'acessoriosocorrencia',
            },
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Informe o modelo', max_length=20, verbose_name='Modelo')),
                ('numeroserie', models.CharField(blank=True, help_text='Informe o número de série', max_length=30, null=True, verbose_name='Número de série')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Arma',
                'verbose_name_plural': 'Armas',
                'db_table': 'arma',
            },
        ),
        migrations.CreateModel(
            name='ArmazenamentoDroga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armazenamento', models.CharField(help_text='Informe o estado da droga', max_length=20, verbose_name='Estado da droga')),
            ],
            options={
                'verbose_name': 'Estado da droga',
                'verbose_name_plural': 'Estados de drogas',
                'db_table': 'armazenamentodroga',
            },
        ),
        migrations.CreateModel(
            name='Calibre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibre', models.CharField(help_text='Informe o calibre', max_length=20, verbose_name='Calibre')),
            ],
            options={
                'verbose_name': 'Calibre',
                'verbose_name_plural': 'Calibres',
                'db_table': 'calibre',
            },
        ),
        migrations.CreateModel(
            name='FabricanteArma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricantearma', models.CharField(help_text='Informe o Fabricante', max_length=255, verbose_name='Fabricante da arma')),
                ('sigla', models.CharField(help_text='Informe a Sigla do fabricante', max_length=20, verbose_name='Sigla do fabricante')),
            ],
            options={
                'verbose_name': 'Fabricante da arma',
                'verbose_name_plural': 'Fabricantes de arma',
                'db_table': 'fabricantearma',
            },
        ),
        migrations.CreateModel(
            name='TipoArma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Informe o tipo de arma', max_length=50, verbose_name='Tipo de arma')),
            ],
            options={
                'verbose_name': 'Tipo de arma',
                'verbose_name_plural': 'Tipos de arma',
                'db_table': 'tipoarma',
            },
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Informe qual o tipo de documento', max_length=30, verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'db_table': 'tipodoc',
            },
        ),
        migrations.CreateModel(
            name='TipoDroga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Informe o tipo', max_length=20, verbose_name='Tipo de droga')),
            ],
            options={
                'verbose_name': 'Tipo de droga',
                'verbose_name_plural': 'Tipos de droga',
                'db_table': 'tipodroga',
            },
        ),
        migrations.CreateModel(
            name='TiposDiversos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Informe qual o tipo de objeto', max_length=30, verbose_name='Tipo de objeto')),
            ],
            options={
                'verbose_name': 'Tipo de objeto',
                'verbose_name_plural': 'Tipos de objeto',
                'db_table': 'tipodiversos',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(help_text='Informe a unidade de medida', max_length=5, verbose_name='Unidade de medida')),
            ],
            options={
                'verbose_name': 'Unidade de medida',
                'verbose_name_plural': 'Unidades de medida',
                'db_table': 'unidademedida',
            },
        ),
        migrations.CreateModel(
            name='VeiculoAcessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('acessoriosocorrencia', models.ForeignKey(help_text='Informe a apreensão da ocorrência', on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.AcessoriosOcorrencia', verbose_name='Apreensão da Ocorrência')),
                ('agenterecebedor', models.ForeignKey(help_text='Informe o Agente recebedor', on_delete=django.db.models.deletion.CASCADE, to='localrecebedor.AgenteRecebedor', verbose_name='Agente Recebedor')),
                ('localrecebedor', models.ForeignKey(help_text='Informe o Local recebedor', on_delete=django.db.models.deletion.CASCADE, to='localrecebedor.LocalRecebedor', verbose_name='Local Recebedor')),
                ('observacao', models.ForeignKey(blank=True, help_text='Informe a Observação', null=True, on_delete=django.db.models.deletion.CASCADE, to='observacao.Observacao', verbose_name='Observação')),
                ('veiculo', models.ForeignKey(help_text='Informe o veículo', on_delete=django.db.models.deletion.CASCADE, to='veiculo.Veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Apreensão de veículo',
                'verbose_name_plural': 'Apreensão de veículos',
                'db_table': 'veiculoacessorio',
            },
        ),
        migrations.CreateModel(
            name='MunicaoAcessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(help_text='Informe a quantidade', verbose_name='Quantidade')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('acessoriosocorrencia', models.ForeignKey(help_text='Informe a apreensão da ocorrência', on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.AcessoriosOcorrencia', verbose_name='Apreensão da Ocorrencia')),
                ('agenterecebedor', models.ForeignKey(help_text='Informe o Agente recebedor', on_delete=django.db.models.deletion.CASCADE, to='localrecebedor.AgenteRecebedor', verbose_name='Agente Recebedor')),
                ('localrecebedor', models.ForeignKey(help_text='Informe o Local recebedor', on_delete=django.db.models.deletion.CASCADE, to='localrecebedor.LocalRecebedor', verbose_name='Local Recebedor')),
                ('municao', models.ForeignKey(help_text='Informe o calibre', on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.Calibre', verbose_name='Calibre')),
                ('observacao', models.ForeignKey(blank=True, help_text='Informe a observação', null=True, on_delete=django.db.models.deletion.CASCADE, to='observacao.Observacao', verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Apreensão de munição',
                'verbose_name_plural': 'Apreensão de munições',
                'db_table': 'municaoacessorio',
            },
        ),
        migrations.CreateModel(
            name='DrogaAcessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(help_text='Informe a Quantidade', verbose_name='Quantidade')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('acessoriosocorrencia', models.ForeignKey(help_text='Informe a apreensão da ocorrência', on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.AcessoriosOcorrencia', verbose_name='Apreensão da Ocorrência')),
                ('agenterecebedor', models.ForeignKey(help_text='Informe o Agente recebedor', on_delete=django.db.models.deletion.CASCADE, to='localrecebedor.AgenteRecebedor', verbose_name='Agente Recebedor')),
                ('armazenamentodroga', models.ForeignKey(help_text='Informe o estado da droga', on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.ArmazenamentoDroga', verbose_name='Estado da droga')),
                ('localrecebedor', models.ForeignKey(help_text='Informe o Local recebedor', on_delete=django.db.models.deletion.CASCADE, to='localrecebedor.LocalRecebedor', verbose_name='Local Recebedor')),
                ('medida', models.ForeignKey(help_text='Informe a unidade de medida', on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.UnidadeMedida', verbose_name='Unidade de medida')),
                ('observacao', models.ForeignKey(blank=True, help_text='Informe a Observação', null=True, on_delete=django.db.models.deletion.CASCADE, to='observacao.Observacao', verbose_name='Observação')),
                ('tipodroga', models.ForeignKey(help_text='Informe a droga', on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.TipoDroga', verbose_name='Droga')),
            ],
            options={
                'verbose_name': 'Apreensão de droga',
                'verbose_name_plural': 'Apreensão de drogas',
                'db_table': 'drogaacessorio',
            },
        ),
        migrations.CreateModel(
            name='DocAcessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Informe o Número', max_length=50, null=True, verbose_name='Número')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('acessoriosocorrencia', models.ForeignKey(help_text='Informe a apreensão da ocorrência', on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.AcessoriosOcorrencia', verbose_name='Apreensão da Ocorrência')),
                ('agenterecebedor', models.ForeignKey(help_text='Informe o Agente recebedor', on_delete=django.db.models.deletion.CASCADE, to='localrecebedor.AgenteRecebedor', verbose_name='Agente Recebedor')),
                ('localrecebedor', models.ForeignKey(help_text='Informe o Local recebedor', on_delete=django.db.models.deletion.CASCADE, to='localrecebedor.LocalRecebedor', verbose_name='Local Recebedor')),
                ('observacao', models.ForeignKey(blank=True, help_text='Informe a Observação', null=True, on_delete=django.db.models.deletion.CASCADE, to='observacao.Observacao', verbose_name='Observação')),
                ('tipodoc', models.ForeignKey(help_text='Informe o tipo de Documento', on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.TipoDoc', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Apreensão de documento',
                'verbose_name_plural': 'Apreensão de documentos',
                'db_table': 'docacessorio',
            },
        ),
        migrations.CreateModel(
            name='DiversosAcessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Informe uma Descrição', verbose_name='Descrição')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('acessoriosocorrencia', models.ForeignKey(help_text='Informe a apreensão da ocorrência', on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.AcessoriosOcorrencia', verbose_name='Apreensão da Ocorrência')),
                ('agenterecebedor', models.ForeignKey(help_text='Informe o Agente recebedor', on_delete=django.db.models.deletion.CASCADE, to='localrecebedor.AgenteRecebedor', verbose_name='Agente Recebedor')),
                ('localrecebedor', models.ForeignKey(help_text='Informe o Local recebedor', on_delete=django.db.models.deletion.CASCADE, to='localrecebedor.LocalRecebedor', verbose_name='Local Recebedor')),
                ('observacao', models.ForeignKey(blank=True, help_text='Informe a Observação', null=True, on_delete=django.db.models.deletion.CASCADE, to='observacao.Observacao', verbose_name='Observação')),
                ('tipodiversos', models.ForeignKey(help_text='Informe o tipo', on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.TiposDiversos', verbose_name='Objeto')),
            ],
            options={
                'verbose_name': 'Apreensão de objeto',
                'verbose_name_plural': 'Apreensão de objetos',
                'db_table': 'diversosacessorio',
            },
        ),
        migrations.CreateModel(
            name='ArmaAcessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('acessoriosocorrencia', models.ForeignKey(help_text='Informe a apreensão da ocorrência', on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.AcessoriosOcorrencia', verbose_name='Apreensão da Ocorrência')),
                ('agenterecebedor', models.ForeignKey(help_text='Informe o Agente recebedor', on_delete=django.db.models.deletion.CASCADE, to='localrecebedor.AgenteRecebedor', verbose_name='Agente Recebedor')),
                ('arma', models.ForeignKey(help_text='Informe a arma', on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.Arma', verbose_name='Arma')),
                ('localrecebedor', models.ForeignKey(help_text='Informe o Local recebedor', on_delete=django.db.models.deletion.CASCADE, to='localrecebedor.LocalRecebedor', verbose_name='Local Recebedor')),
                ('observacao', models.ForeignKey(blank=True, help_text='Informe a Observação', null=True, on_delete=django.db.models.deletion.CASCADE, to='observacao.Observacao', verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Apreensão de arma',
                'verbose_name_plural': 'Apreensão de armas',
                'db_table': 'armaacessorio',
            },
        ),
        migrations.AddField(
            model_name='arma',
            name='calibre',
            field=models.ForeignKey(blank=True, help_text='Informe o calibre', null=True, on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.Calibre', verbose_name='Calibre'),
        ),
        migrations.AddField(
            model_name='arma',
            name='fabricantearma',
            field=models.ForeignKey(blank=True, help_text='Informe o fabricante', null=True, on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.FabricanteArma', verbose_name='Fabricante da arma'),
        ),
        migrations.AddField(
            model_name='arma',
            name='tipoarma',
            field=models.ForeignKey(help_text='Informe o tipo de arma', on_delete=django.db.models.deletion.CASCADE, to='acessoriosocorrencia.TipoArma', verbose_name='Tipo de arma'),
        ),
    ]
