# Generated by Django 3.0.5 on 2020-08-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocorrencia', '0001_initial'),
        ('acessoriosocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessoriosocorrencia',
            name='ocorrencia',
            field=models.ForeignKey(help_text='Informe a Ocorrência', on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.Ocorrencia', verbose_name='Ocorrência'),
        ),
    ]
