# Generated by Django 3.0.5 on 2020-08-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Informe a categoria', max_length=50, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de veículo',
                'verbose_name_plural': 'Categorias de veículo',
                'db_table': 'categoriaveiculo',
            },
        ),
        migrations.CreateModel(
            name='MarcaVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Informe a marca', max_length=50, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca de veículo',
                'verbose_name_plural': 'Marcas de veículo',
                'db_table': 'marcaveiculo',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Informe o modelo', max_length=80, verbose_name='Modelo')),
                ('cor', models.CharField(help_text='Informe a cor', max_length=10, verbose_name='Cor')),
                ('chassi', models.CharField(blank=True, help_text='Informe o chassi', max_length=30, null=True, verbose_name='Chassi')),
                ('placa', models.CharField(blank=True, help_text='Informe a placa', max_length=10, null=True, verbose_name='Placa')),
                ('ano', models.IntegerField(blank=True, help_text='Informe o ano', null=True, verbose_name='Ano')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('categoria', models.ForeignKey(help_text='Informe a categoria', on_delete=django.db.models.deletion.CASCADE, to='veiculo.CategoriaVeiculo', verbose_name='Categoria')),
                ('marca', models.ForeignKey(help_text='Informe a marca', on_delete=django.db.models.deletion.CASCADE, to='veiculo.MarcaVeiculo', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'veiculo',
            },
        ),
    ]
