# Generated by Django 3.0.5 on 2020-08-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observacao', '0001_initial'),
        ('guarnicao', '0002_auto_20200813_0040'),
        ('policial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitantenome', models.CharField(help_text='Informe o nome do solicitante', max_length=100, verbose_name='Nome do solicitante')),
                ('solicitantecontato', models.CharField(blank=True, help_text='Informe o contato do solicitante', max_length=80, null=True, verbose_name='Contato do solicitante')),
                ('titulo', models.CharField(help_text='Informe o título', max_length=100, verbose_name='Título')),
                ('datasolicitacao', models.DateTimeField(verbose_name='Data da solicitação')),
                ('datainicio', models.DateTimeField(verbose_name='Data de início')),
                ('datatermino', models.DateTimeField(verbose_name='Data de término')),
                ('numeroopo', models.CharField(help_text='Informe o número da OPO', max_length=50, unique=True, verbose_name='Número da OPO')),
                ('local', models.CharField(help_text='Informe o local da OPO', max_length=255, verbose_name='Local da OPO')),
                ('armamento', models.CharField(help_text='Informe o armamento', max_length=100, verbose_name='Armamento')),
                ('uniforme', models.CharField(help_text='Informe o uniforme', max_length=100, verbose_name='Uniforme')),
                ('designado', models.CharField(choices=[('coordenadordearea', 'COORDENADOR DE ÁREA'), ('cicom', 'CICOM'), ('comandantecia', 'COMANDANTE DE CIA')], help_text='Designe a OPO', max_length=17, verbose_name='Designado para')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('observacao', models.ForeignKey(blank=True, help_text='Informe a observação', null=True, on_delete=django.db.models.deletion.CASCADE, to='observacao.Observacao', verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Ordem de Policiamento Ostensivo',
                'verbose_name_plural': 'Ordens de Policiamento Ostensivo',
                'db_table': 'opo',
            },
        ),
        migrations.CreateModel(
            name='OPOTipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Informe o tipo de evento', max_length=50, verbose_name='Tipo de evento')),
            ],
            options={
                'verbose_name': 'Tipo de evento',
                'verbose_name_plural': 'Tipos de evento',
                'db_table': 'opotipoevento',
            },
        ),
        migrations.CreateModel(
            name='OPORelatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(blank=True, help_text='Informe o local', max_length=255, null=True, verbose_name='Local')),
                ('status', models.CharField(choices=[('pendente', 'PENDENTE'), ('andamento', 'EM ANDAMENTO'), ('finalizada', 'FINALIZADA')], default='pendente', help_text='Informe o status', max_length=10, verbose_name='Status')),
                ('relatorio', models.TextField(blank=True, null=True, verbose_name='Relatório')),
                ('dataexecucao', models.DateTimeField(verbose_name='Data da execução')),
                ('datafinalizacao', models.DateTimeField(verbose_name='Data de finalização')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('designador', models.ForeignKey(blank=True, help_text='Informe quem designou', null=True, on_delete=django.db.models.deletion.CASCADE, to='policial.Policial', verbose_name='Designador')),
                ('guarnicao', models.ForeignKey(blank=True, help_text='Informe a guarnição', null=True, on_delete=django.db.models.deletion.CASCADE, to='guarnicao.Guarnicao', verbose_name='Guarnição')),
                ('opo', models.ForeignKey(help_text='Informe o OPO', on_delete=django.db.models.deletion.CASCADE, to='opo.OPO', verbose_name='OPO')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'db_table': 'oporelatorio',
            },
        ),
        migrations.CreateModel(
            name='OPOComandantesCIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataatualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('comandante', models.ForeignKey(help_text='Informe o comandante de CIA', on_delete=django.db.models.deletion.CASCADE, to='policial.Policial', verbose_name='Comandante de CIA')),
                ('opo', models.ForeignKey(help_text='Informe o OPO', on_delete=django.db.models.deletion.CASCADE, to='opo.OPO', verbose_name='OPO')),
            ],
            options={
                'verbose_name': 'OPO comandante de CIA',
                'verbose_name_plural': 'OPOs comandante de CIA',
                'db_table': 'opocomandantescia',
            },
        ),
        migrations.AddField(
            model_name='opo',
            name='opotipoevento',
            field=models.ForeignKey(help_text='Informe o tipo de evento', on_delete=django.db.models.deletion.CASCADE, to='opo.OPOTipoEvento', verbose_name='Tipo de evento'),
        ),
    ]
