# Generated by Django 3.0.5 on 2020-08-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opo',
            name='datatermino',
            field=models.DateTimeField(null=True, verbose_name='Data de término'),
        ),
    ]
