# Generated by Django 3.0.5 on 2020-09-15 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policial', '0001_initial'),
        ('opo', '0004_auto_20200821_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='oporelatorio',
            name='finalizadopor',
            field=models.ForeignKey(blank=True, help_text='Finalizado por', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opo_finalizadopor', to='policial.Policial', verbose_name='Finalizado por'),
        ),
    ]
