# Generated by Django 3.0.5 on 2020-09-17 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opo', '0005_oporelatorio_finalizadopor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oporelatorio',
            name='finalizadopor',
        ),
    ]
