# Generated by Django 3.0.5 on 2020-09-17 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0002_ocorrencia_finalizadopor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='finalizadopor',
        ),
    ]
