# Generated by Django 3.0.5 on 2020-09-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0004_auto_20200917_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observacaoocorrencia',
            options={'verbose_name': 'Aditamento da ocorrência', 'verbose_name_plural': 'Aditamentos da ocorrência'},
        ),
        migrations.AddField(
            model_name='observacaoocorrencia',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Está ativa?'),
        ),
    ]
