# Generated by Django 3.0.5 on 2020-09-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0005_auto_20200919_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='status_previa',
            field=models.BooleanField(default=True, verbose_name='Status de pré-visualização'),
        ),
    ]
