# Generated by Django 3.0.5 on 2020-09-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policial', '0001_initial'),
        ('ocorrencia', '0006_ocorrencia_status_previa'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacaoocorrencia',
            name='autor',
            field=models.ForeignKey(default=1, help_text='Informe o autor', on_delete=django.db.models.deletion.CASCADE, to='policial.Policial', verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
