from django.urls import path
from .views import (
    TipoServicoListCreateView,
    TipoServicoDetailsUpdateDeleteView,
    ModalidadedePoliciamentoListCreateView,
    ModalidadedePoliciamentoDetailsUpdateDeleteView,
    CompanhiaListCreateView,
    CompanhiaDetailsUpdateDeleteView,
    GuarnicaoListCreateView,
    GuarnicaoDetailsUpdateDeleteView,
    GuarnicaoAITListCreateView,
    GuarnicaoAITDetailsUpdateDeleteView,
    GuarnicaoRRDListCreateView,
    GuarnicaoRRDDetailsUpdateDeleteView,
    GuarnicaoTRAVListCreateView,
    GuarnicaoTRAVDetailsUpdateDeleteView,
    PermutaListCreateView,
    PermutaDetailsUpdateDeleteView,




    GuarnicaoAtivaView
)

urlpatterns = [
    path(
        'ativa/<int:id>/',
        GuarnicaoAtivaView.as_view(),
        name='ativa'),
    path(
        'tiposervico/',
        TipoServicoListCreateView.as_view(),
        name='create'),
    path(
        'tiposervico/<int:pk>/',
        TipoServicoDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'modalidadepoliciamento/',
        ModalidadedePoliciamentoListCreateView.as_view(),
        name='create'),
    path(
        'modalidadepoliciamento/<int:pk>/',
        ModalidadedePoliciamentoDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'companhia/',
        CompanhiaListCreateView.as_view(),
        name='create'),
    path(
        'companhia/<int:pk>/',
        CompanhiaDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        '',
        GuarnicaoListCreateView.as_view(),
        name='create'),
    path(
        '<int:pk>/',
        GuarnicaoDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'ait/',
        GuarnicaoAITListCreateView.as_view(),
        name='create'),
    path(
        'ait/<int:pk>/',
        GuarnicaoAITDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'rrd/',
        GuarnicaoRRDListCreateView.as_view(),
        name='create'),
    path(
        'rrd/<int:pk>/',
        GuarnicaoRRDDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'trav/',
        GuarnicaoTRAVListCreateView.as_view(),
        name='create'),
    path(
        'trav/<int:pk>/',
        GuarnicaoTRAVDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'permuta/',
        PermutaListCreateView.as_view(),
        name='create'),
    path(
        'permuta/<int:pk>/',
        PermutaDetailsUpdateDeleteView.as_view(),
        name='detalhe')
]
