from django.urls import path
from .views import (
    CalibreListCreateView,
    CalibreDetailsUpdateDeleteView,
    FabricanteArmaListCreateView,
    FabricanteArmaDetailsUpdateDeleteView,
    UnidadeMedidaListCreateView,
    UnidadeMedidaDetailsUpdateDeleteView,
    MunicaoAcessorioListCreateView,
    MunicaoAcessorioDetailsUpdateDeleteView,
    VeiculoAcessorioListCreateView,
    VeiculoAcessorioDetailsUpdateDeleteView,
    TipoDocListCreateView,
    TipoDocDetailsUpdateDeleteView,
    DocAcessorioListCreateView,
    DocAcessorioDetailsUpdateDeleteView,
    TiposDiversosListCreateView,
    TiposDiversosDetailsUpdateDeleteView,
    DiversosAcessorioListCreateView,
    DiversosAcessorioDetailsUpdateDeleteView,
    ArmaListCreateView,
    ArmaDetailsUpdateDeleteView,
    TipoArmaListCreateView,
    TipoArmaDetailsUpdateDeleteView,
    ArmaAcessorioListCreateView,
    ArmaAcessorioDetailsUpdateDeleteView,
    TipoDrogaListCreateView,
    TipoDrogaDetailsUpdateDeleteView,
    ArmazenamentoDrogaListCreateView,
    ArmazenamentoDrogaDetailsUpdateDeleteView,
    DrogaAcessorioListCreateView,
    DrogaAcessorioDetailsUpdateDeleteView,
    AcessoriosOcorrenciaListCreateView,
    AcessoriosOcorrenciaDetailsUpdateDeleteView
)

urlpatterns = [
    path(
        'acessoriosocorrencia/',
        AcessoriosOcorrenciaListCreateView.as_view(),
        name='create'),

    path(
        'acessoriosocorrencia/<int:pk>/',
        AcessoriosOcorrenciaDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'calibre/',
        CalibreListCreateView.as_view(),
        name='create'),

    path(
        'calibre/<int:pk>/',
        CalibreDetailsUpdateDeleteView.as_view(),
        name='detalhe'),


    path(
        'fabricantearma/',
        FabricanteArmaListCreateView.as_view(),
        name='create'),
    path(
        'fabricantearma/<int:pk>/',
        FabricanteArmaDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'unidademedida/',
        UnidadeMedidaListCreateView.as_view(),
        name='create'),
    path(
        'unidademedida/<int:pk>/',
        UnidadeMedidaDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'municaoacessorio/',
        MunicaoAcessorioListCreateView.as_view(),
        name='create'),
    path(
        'municaoacessorio/<int:pk>/',
        MunicaoAcessorioDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'veiculoacessorio/',
        VeiculoAcessorioListCreateView.as_view(),
        name='create'),
    path(
        'veiculoacessorio/<int:pk>/',
        VeiculoAcessorioDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'tipodoc/',
        TipoDocListCreateView.as_view(),
        name='create'),
    path(
        'tipodoc/<int:pk>/',
        TipoDocDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'docacessorio/',
        DocAcessorioListCreateView.as_view(),
        name='create'),
    path(
        'docacessorio/<int:pk>/',
        DocAcessorioDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'tiposdiversos/',
        TiposDiversosListCreateView.as_view(),
        name='create'),
    path(
        'tiposdiversos/<int:pk>/',
        TiposDiversosDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'diversosacessorio/',
        DiversosAcessorioListCreateView.as_view(),
        name='create'),
    path(
        'diversosacessorio/<int:pk>/',
        DiversosAcessorioDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'arma/',
        ArmaListCreateView.as_view(),
        name='create'),
    path(
        'tipoarma/',
        TipoArmaListCreateView.as_view(),
        name='create'),
    path(
        'tipoarma/<int:pk>/',
        TipoArmaDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'arma/<int:pk>/',
        ArmaDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'armaacessorio/',
        ArmaAcessorioListCreateView.as_view(),
        name='create'),
    path(
        'armaacessorio/<int:pk>/',
        ArmaAcessorioDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'tipodroga/',
        TipoDrogaListCreateView.as_view(),
        name='create'),
    path(
        'tipodroga/<int:pk>/',
        TipoDrogaDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'armazenamentodroga/',
        ArmazenamentoDrogaListCreateView.as_view(),
        name='create'),
    path(
        'armazenamentodroga/<int:pk>/',
        ArmazenamentoDrogaDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
    path(
        'drogaacessorio/',
        DrogaAcessorioListCreateView.as_view(),
        name='create'),
    path(
        'drogaacessorio/<int:pk>/',
        DrogaAcessorioDetailsUpdateDeleteView.as_view(),
        name='detalhe'),
]
