name: Django CI

on:
  push:
    branches: [ rota-login-personalizada ]
  pull_request:
    branches: [ master, v2.2 ]

  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Makemigratios
      run:
        python manage.py makemigrations
    - name: Migrate
      run:
        python manage.py migrate
    - name: Install database
      run:
        python manage.py loaddata jsonfiles_data/BANCO_23.json
    - name: Run Tests
      run: |
        python manage.py test
